### ISSUE TITLE
Asserting call to method with array argument fails

### ISSUE THREAD

**Issue by thatguysimon** [bogdanvlviv/minitest-mock_expectations#4]
Hi, great job on this gem!
I found a pretty serious bug though :(

If you try to assert a call to a method that takes an array as its argument:
```ruby
assert_called_with(Tempfile, :new, [['hello', '.jpg']]) do
  file = Tempfile.new(['hello', '.jpg'])  
end
```
Running the above code will result in:
```
ArgumentError: mocked method :call expects 2 arguments, got 1
from .../ruby-2.6.3/gems/minitest-5.14.0/lib/minitest/mock.rb:150:in `method_missing'
```
This happens due to a collision with the feature of being able to pass an array of different sets of arguments that the method can be called with.

I suggest changing the interface of the multiple arguments feature to the following (which will also allow providing a different return value for each set of arguments):
```ruby
expectations = [
  { 
    expected_args: ["Thanks for sharing this."],
    return_value: mocked_comment_1
  },
  { 
    expected_args:  ["Thanks!"],
    return_value: mocked_comment_2 
  }
]

assert_called_with(@post, :add_comment, expectations: expectations) do
  @post.add_comment("Thanks for sharing this.")
  @post.add_comment("Thanks!")
end
```

Shall I open a PR for this?

**Comment by bogdanvlviv** [comment]
Hey @thatguysimon, thanks for raising the issue. :bowing_man:  I'll try to get back to this later this week.

**Comment by bogdanvlviv** [comment]
@thatguysimon I opened a PR to fix an issue with the example: https://github.com/bogdanvlviv/minitest-mock_expectations/pull/5

```ruby
assert_called_with(Tempfile, :new, [['hello', '.jpg']]) do
  file = Tempfile.new(['hello', '.jpg'])  
end
```

Also added tests and docs to clarify `assert_called_with`. Please let me know what you think about that PR. Thanks.

**Comment by bogdanvlviv** [comment]
Hi again @thatguysimon. I tried the same fix on Rails(https://github.com/rails/rails/pull/39033) and we we found the real bug it causes. For instance(https://github.com/rails/rails/pull/39033#discussion_r414488996), it isnt' possible to assert:

```ruby
@object.push([ 1 ], [ 2 ])
```
anymore.

So to solve you issue with

```ruby
assert_called_with(Tempfile, :new, [['hello', '.jpg']]) do
  file = Tempfile.new(['hello', '.jpg'])  
end
```

you should change your code to


```ruby
assert_called_with(Tempfile, :new, [ [['hello', '.jpg']] ]) do
  file = Tempfile.new(['hello', '.jpg'])  
end
```

I gonna revert this change and release 1.1.3 :sweat_smile:  because of that:


https://github.com/bogdanvlviv/minitest-mock_expectations/pull/7
https://github.com/bogdanvlviv/minitest-mock_expectations/releases/tag/v1.1.3
https://rubygems.org/gems/minitest-mock_expectations/versions/1.1.3
